#!/usr/bin/env python3
#
#    _____     _                _____           _       _
#   |_   _|   | |              /  ___|         (_)     | |
#     | | ___ | | _____ _ __   \ `--.  ___ _ __ _ _ __ | |_
#     | |/ _ \| |/ / _ \ '_ \   `--. \/ __| '__| | '_ \| __|
#     | | (_) |   <  __/ | | | /\__/ / (__| |  | | |_) | |_
#     \_/\___/|_|\_\___|_| |_| \____/ \___|_|  |_| .__/ \__|
#                                                | |
#                                                |_|
#
#   run ./token
#   to generate a token to access your jupyter-notebook


import hashlib
import argparse
import sys

token = str(input('token: '))
token_sha1 = hashlib.sha1(token.encode('utf-8')).hexdigest()
print (f'Use the below line as token argument in your .env:\n\nsha1:{token_sha1}')

